# Generated by Django 3.0 on 2023-08-24 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20230823_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='data_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='data_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='data_created',
            new_name='date_created',
        ),
    ]
